const postsData = [
    {
        id: 10,
        title: "Technology Blogs 1 -- Wired",
        desc: "<p>Wired is a massively popular publication, good at capturing real insights into the tech world, no stranger to topics like technology, entertainment, science, culture, politics, and social media. Informed and comprehensive, Wired is basically the perfect tech blog to follow.</p><p><br></p><p>This unique blog is dedicated to modern life and the technology industry and answers every question related to tech trends, gadget reviews, and the latest updates.</p><p><br></p><p>Wired is ranked as one of the best tech blogs for professionals in every industry and delivers great ideas for presenting the most relevant topics to your audience.</p>",
        img: "1713203944706pexels-alex-andrews-821652.jpg",
        date: "2024-04-15 10:59:04",
        uid: 2,
        cat: "technology",
    },
    {
        id: 11,
        title: "Tech Blog - TechCrunch",
        desc: "<p>Invest yourself in the business verse of the tech world with one of the most popular technology blogs thriving this year-&nbsp;<strong>TechCrunch</strong>.</p><p>The blog publishes&nbsp;<strong>content on businesses related to tech</strong>, analysis of emerging trends in tech, technology news, and listings of new tech products in the market. It is one of the first publications to report broadly on tech startups and funding rounds.</p><p>TechCrunch offers knowledge about new gizmos and business-related apps. It is like a reservoir of information on Internet companies &amp; startups around the world.</p><p><br></p>",
        img: "1713204033818pexels-elina-sazonova-1850617.jpg",
        date: "2024-04-15 11:00:33",
        uid: 2,
        cat: "technology",
    },
    {
        id: 12,
        title: "Design Blog - Hi-Fructose ",
        desc: '<p><span style="background-color: rgb(255, 255, 255); color: rgb(36, 36, 36);">Hi-Fructose was founded by two artists by the name of Attaboy and Annie Owen in the year 2005. It is a magazine that is published quarterly. The art blog part is headed by Andy Smith. Hi-Fructose revolves around contemporary art and showcases the best artists of recent times. There is no fixed genre that it emphasizes. Each post highlights the works of a different artist, focusing on one notable work. A typical Hi-Fructose post also describes how the artist came up with the idea and the process behind the creation of the work. The post contains information about the artist and his/her quotes. Hi-Fructose appreciates and celebrates original artwork and inspires new artists to come up with better works. The blog is full of talented contributors and readers can expect as many as four posts every day!&nbsp;</span></p>',
        img: "1713204132557pexels-evie-shaffer-2395251.jpg",
        date: "2024-04-15 11:02:12",
        uid: 2,
        cat: "design",
    },
    {
        id: 13,
        title: "Art Blog 1- Colossal",
        desc: '<p><span style="background-color: rgb(255, 255, 255); color: rgb(81, 81, 81);">An international online platform for contemporary art and visual expression. The art included explores a range of creative disciplines, featuring art, design, craft, and photography. Interviews with artists also present.</span></p>',
        img: "1713204943628pexels-motional-studio-1081685.jpg",
        date: "2024-04-15 11:15:43",
        uid: 1,
        cat: "art",
    },
    {
        id: 14,
        title: "Art Blog - Artsy",
        desc: '<p><span style="background-color: var(--ricos-custom-p-background-color,unset);">At the forefront of contemporary art, Artsy is a global organization with a mission to support artists around the world. Describing themselves as ‘a platform for collecting and discovering art,’ Artsy’s blog really is a great place to start if you want to get yourself better acquainted with the artists of today.</span></p><p><br></p><p><span style="background-color: var(--ricos-custom-p-background-color,unset);">Publishing daily, or even a few times a day, this blog is packed full of fascinating content. You’ll find highbrow artist interviews, reviews, gallery and exhibition recommendations, plus news from around the art world.</span></p><p><br></p><p><span style="background-color: var(--ricos-custom-p-background-color,unset);">There’s also a selection of in-depth thought pieces examining various art movements, as well as topics ranging from feminism, to the return of craft and more.</span></p><p><br></p>',
        img: "1713204996328pexels-mart-production-8076182.jpg",
        date: "2024-04-15 11:16:36",
        uid: 1,
        cat: "art",
    },
    {
        id: 15,
        title: "Science Blog ",
        desc: "<p>At the nexus of art and health are two leading practitioners of music and biomedical research—Renée Fleming and Francis Collins. Both advocate for a better understanding of the connections between music and the brain (see the Editorial). I spoke to them recently about their shared interest in this area, their hopes for the future of this young field of study, and Renée’s new book, Music and Mind: Harnessing the Arts for Health and Wellness. Here’s the full text of our interview.</p><p><br></p><p><br></p><p><br></p>",
        img: "1713205155398pexels-ravi-kant-4533596.jpg",
        date: "2024-04-15 11:19:15",
        uid: 1,
        cat: "science",
    },
    {
        id: 16,
        title: "Science Blog 2",
        desc: "<p>Last week, U.S. News &amp; World Report issued their rankings of the best undergraduate programs in the United States. To counter criticism that the rankings did not adequately recognize universities for supporting low-income students and social mobility, the magazine recently made substantial changes to the formula. As a result, the rankings of many public universities improved dramatically, and a few private universities dropped to a lower position. The reactions from some institutions revealed that they prioritize rankings over other aspects of their missions.</p><p><br></p>",
        img: "1713205250624pexels-cameron-casey-1722183.jpg",
        date: "2024-04-15 11:20:50",
        uid: 1,
        cat: "science",
    },
];
export default postsData;
